run:
  tests: false
issues:
  exclude-dirs:
    - cmd
    - dist
    - test-data
linters:
  disable:
    - lll
    - gci
    - wsl
    - godot
    - tagliatelle
    - exhaustruct
    - nakedret
    - gofumpt
    - cyclop
    - wrapcheck
    - varnamelen
    - nlreturn
    - gomnd
  enable-all: true
linters-settings:
  funlen:
    lines: 80
    statements: 50
  gocognit:
    min-complexity: 90
  gocyclo:
    min-complexity: 50