project_name: syno-cli
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
    flags:
      - -trimpath
    main: ./cmd/syno-cli
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
dockers:
  - image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
      - "reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
    use: buildx
    goarch: arm64
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/arm64/v8"
docker_manifests:
  - name_template: "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
  - name_template: "reddec/{{ .ProjectName }}:{{ .Version }}"
    image_templates:
      - "reddec/{{ .ProjectName }}:{{ .Version }}-amd64"
      - "reddec/{{ .ProjectName }}:{{ .Version }}-arm64v8"
release:
  footer: |
    ## Docker images
    
        ghcr.io/reddec/{{ .ProjectName }}:{{ .Version }}
        reddec/{{ .ProjectName }}:{{ .Version }}
    
    Both images supports `arm64` and `amd64` and built on top of alpine

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
