name: Build and release
on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Log in to the main registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: reddec
          password: ${{ secrets.DOCKERIO_PASSWORD }}
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.23'
        id: go
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 0
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Pull tag
        run: git fetch --tags
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}